In [1]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('penguins.csv')

In [5]:
df.head()

rowid species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0      1  Adelie  Torgersen            39.1           18.7              181.0   
1      2  Adelie  Torgersen            39.5           17.4              186.0   
2      3  Adelie  Torgersen            40.3           18.0              195.0   
3      4  Adelie  Torgersen             NaN            NaN                NaN   
4      5  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  year  
0       3750.0    male  2007  
1       3800.0  female  2007  
2       3250.0  female  2007  
3          NaN     NaN  2007  
4       3450.0  female  2007

In [7]:
df1=df.iloc[:,3:7]
df1.head()

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
0            39.1           18.7              181.0       3750.0
1            39.5           17.4              186.0       3800.0
2            40.3           18.0              195.0       3250.0
3             NaN            NaN                NaN          NaN
4            36.7           19.3              193.0       3450.0

In [9]:
df2=df1.dropna()
df2.head()

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
0            39.1           18.7              181.0       3750.0
1            39.5           17.4              186.0       3800.0
2            40.3           18.0              195.0       3250.0
4            36.7           19.3              193.0       3450.0
5            39.3           20.6              190.0       3650.0

In [10]:
print(df2.cov())

                   bill_length_mm  bill_depth_mm  flipper_length_mm  \
bill_length_mm          29.807054      -2.534234          50.375765   
bill_depth_mm           -2.534234       3.899808         -16.212950   
flipper_length_mm       50.375765     -16.212950         197.731792   
body_mass_g           2605.591912    -747.370093        9824.416062   

                     body_mass_g  
bill_length_mm       2605.591912  
bill_depth_mm        -747.370093  
flipper_length_mm    9824.416062  
body_mass_g        643131.077327  


In [12]:
data=df2.to_numpy()
data_center=data-np.mean(data,axis=0)
cov_matrix=1/data.shape[0]* np.dot(data_center.T,data_center)
print(cov_matrix)


[[ 2.97198992e+01 -2.52682389e+00  5.02284677e+01  2.59797322e+03]
 [-2.52682389e+00  3.88840506e+00 -1.61655441e+01 -7.45184800e+02]
 [ 5.02284677e+01 -1.61655441e+01  1.97153628e+02  9.79568970e+03]
 [ 2.59797322e+03 -7.45184800e+02  9.79568970e+03  6.41250577e+05]]


In [14]:
# 
df_sp=df.iloc[:,1]
df_sp=df_sp.dropna()
df_sp.head()

0    Adelie
1    Adelie
2    Adelie
3    Adelie
4    Adelie
Name: species, dtype: object

In [19]:
p=df_sp.value_counts()/df_sp.shape[0]
p=p.to_numpy()
print(np.diag(p))
cov_matrix=np.diag(p)-np.outer(p,p)
print(cov_matrix)

[[0.44186047 0.         0.        ]
 [0.         0.36046512 0.        ]
 [0.         0.         0.19767442]]
[[ 0.24661979 -0.15927528 -0.08734451]
 [-0.15927528  0.23053002 -0.07125473]
 [-0.08734451 -0.07125473  0.15859924]]
